#!/bin/sh
# audio-separator launcher: same PYTHONPATH workaround as demucs-run
# (sandbox breaks CPython venv detection).
export PYTHONPATH="/home/bronder/source/guitarTabsMe-Off/.venv-demucs/lib/python3.14/site-packages${PYTHONPATH:+:$PYTHONPATH}"
exec /home/bronder/source/guitarTabsMe-Off/.venv-demucs/bin/audio-separator "$@"
